# Hyprlock colors.
$accent = rgb({color4.strip})
$accentAlpha = {color4.strip}

$surface0 = rgb({background.strip})

$text = rgba({foreground.strip}aa)
$textAlpha = rgba({foreground.strip}77)

$red = rgb({color1.strip})
$yellow = rgb({color3.strip})
