# https://terminalcolors.com/themes/noctis/minimus/

# The basic colors
foreground              #c5cdd3
background              #0e1920
selection_foreground    #c5cdd3
selection_background    #213541

# Cursor colors
cursor                  #c5cdd3
cursor_text_color       #0e1920

# URL underline color when hovering with mouse
url_color               #68a4ca

# Kitty window border colors
active_border_color     #6196b8
inactive_border_color   #425866
bell_border_color       #c8a984

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0e1920
active_tab_background   #68a4ca
inactive_tab_foreground #c5cdd3
inactive_tab_background #425866
tab_bar_background      #0e1920

# Colors for marks (marked text in the terminal)
mark1_foreground #0e1920
mark1_background #6196b8
mark2_foreground #0e1920
mark2_background #68a4ca
mark3_foreground #0e1920
mark3_background #72b7c0

# The 16 terminal colors

# black
color0  #182a35
color8  #425866

# red
color1  #c08872
color9  #ca8468

# green
color2  #72c09f
color10 #84c8ab

# yellow
color3  #c8a984
color11 #d1aa7b

# blue
color4  #6196b8
color12 #68a4ca

# magenta
color5  #c28097
color13 #c88da2

# cyan
color6  #72b7c0
color14 #84c0c8

# white
color7  #c5cdd3
color15 #c5d1d3