# https://terminalcolors.com/themes/nordic/default/

# The basic colors
foreground              #bbc3d4
background              #242933
selection_foreground    #bbc3d4
selection_background    #1b1f26

# Cursor colors
cursor                  #bbc3d4
cursor_text_color       #191d24

# URL underline color when hovering with mouse
url_color               #88c0d0

# Kitty window border colors
active_border_color     #5e81ac
inactive_border_color   #3b4252
bell_border_color       #ebcb8b

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #191d24
active_tab_background   #88c0d0
inactive_tab_foreground #bbc3d4
inactive_tab_background #3b4252
tab_bar_background      #242933

# Colors for marks (marked text in the terminal)
mark1_foreground #191d24
mark1_background #5e81ac
mark2_foreground #191d24
mark2_background #88c0d0
mark3_foreground #191d24
mark3_background #8fbcbb

# The 16 terminal colors

# black
color0  #191d24
color8  #3b4252

# red
color1  #bf616a
color9  #c5727a

# green
color2  #a3be8c
color10 #b1c89d

# yellow
color3  #ebcb8b
color11 #efd49f

# blue
color4  #5e81ac
color12 #88c0d0

# magenta
color5  #b48ead
color13 #be9d88

# cyan
color6  #8fbcbb
color14 #9fc6c5

# white
color7  #bbc3d4
color15 #d8dee9